"""UpdateDB

Revision ID: 63b2667118f3
Revises: 
Create Date: 2022-12-04 13:42:40.820910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b2667118f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textdocs', sa.Column('doc_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('textdocs', 'doc_text')
    # ### end Alembic commands ###
